const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path');
const {createController, captureFocus} = require('../review-autosave.js');
const tick = () => new Promise(resolve => setImmediate(resolve));
const deferred = () => { let resolve, reject; const promise = new Promise((a,b) => { resolve=a; reject=b; }); return {promise,resolve,reject}; };
function fixture() {
  const f={id:'a',value:'',saved:'',valid:true,busy:false,calls:[],states:[],timers:new Map(),serial:0};
  f.save=async()=>{f.saved=f.value;};
  f.controller=createController({getReviewId:()=>f.id,hasDraft:()=>f.value!==f.saved,isValid:()=>f.valid,isBusy:()=>f.busy,
    save:()=>{f.calls.push({id:f.id,value:f.value});return f.save();},onState:state=>f.states.push(state),
    setTimer:(fn,ms)=>{const id=++f.serial;f.timers.set(id,{fn,ms});return id;},clearTimer:id=>f.timers.delete(id),
    sleep:async()=>{f.busy=false;}});
  f.change=value=>{f.value=value;f.controller.schedule();};
  f.advance=async()=>{const [id,timer]=f.timers.entries().next().value||[];assert.ok(timer,'expected scheduled work');f.timers.delete(id);timer.fn();await tick();};
  return f;
}
test('successive edits debounce into one latest-value save',async()=>{const f=fixture();f.change('1');f.change('12');f.change('123');assert.equal(f.timers.size,1);assert.equal(f.calls.length,0);await f.advance();assert.deepEqual(f.calls,[{id:'a',value:'123'}]);assert.equal(f.controller.status,'saved');});
test('readonly renders and reverting an unsent edit leave the server unchanged',async()=>{const f=fixture();f.controller.schedule();assert.equal(f.timers.size,0);f.change('x');f.change('');assert.equal(f.timers.size,0);assert.equal(f.calls.length,0);});
test('edits during a request stay dirty and run serially afterward',async()=>{const f=fixture(),d=deferred();f.save=()=>d.promise;f.change('first');await f.advance();f.change('second');assert.equal(f.calls.length,1);assert.equal(f.controller.hasPending(),true);f.saved='first';d.resolve();await tick();assert.equal(f.controller.status,'pending');f.save=async()=>{f.saved=f.value;};await f.advance();assert.equal(f.calls.length,2);assert.equal(f.saved,'second');});
test('reverting during an in-flight request saves the reversal',async()=>{const f=fixture(),d=deferred();f.save=()=>d.promise;f.change('first');await f.advance();f.change('');assert.equal(f.controller.hasPending(),true);f.saved='first';d.resolve();await tick();f.save=async()=>{f.saved=f.value;};await f.advance();assert.equal(f.calls.length,2);assert.equal(f.saved,'');});
test('flush immediately saves before switching records',async()=>{const f=fixture();f.change('ready');assert.equal(await f.controller.flush(),true);assert.equal(f.calls.length,1);assert.equal(f.timers.size,0);assert.equal(f.controller.hasPending(),false);});
test('flush joins an in-flight request and drains newer edits',async()=>{const f=fixture(),d=deferred();f.save=()=>d.promise;f.change('first');await f.advance();const flushed=f.controller.flush();f.change('last');f.saved='first';f.save=async()=>{f.saved=f.value;};d.resolve();assert.equal(await flushed,true);assert.deepEqual(f.calls.map(c=>c.value),['first','last']);});
test('busy collaboration refresh defers automatic writes',async()=>{const f=fixture();f.busy=true;f.change('x');await f.advance();assert.equal(f.calls.length,0);f.busy=false;await f.advance();assert.equal(f.calls.length,1);});
test('explicit flush waits for the shared lock',async()=>{const f=fixture();f.busy=true;f.change('x');assert.equal(await f.controller.flush(),true);assert.equal(f.calls.length,1);});
test('invalid numeric input preserves draft until corrected',async()=>{const f=fixture();f.valid=false;f.change('invalid');assert.equal(f.controller.status,'invalid');assert.equal(await f.controller.flush(),false);assert.equal(f.calls.length,0);f.valid=true;f.change('3.25');await f.advance();assert.equal(f.saved,'3.25');});
test('invalid input entered during save stays visibly pending',async()=>{const f=fixture(),d=deferred();f.save=()=>d.promise;f.change('2');await f.advance();f.valid=false;f.controller.schedule();f.saved='2';d.resolve();await tick();assert.equal(f.controller.status,'invalid');assert.equal(f.controller.hasPending(),true);});
test('network errors retry at bounded exponential intervals',async()=>{const f=fixture();f.save=async()=>{throw new Error('offline');};f.change('x');await f.advance();for(const ms of [1000,2000,4000]){assert.equal([...f.timers.values()][0].ms,ms);await f.advance();}assert.equal(f.calls.length,4);assert.equal(f.timers.size,0);assert.equal(f.controller.hasPending(),true);});
test('conflicts preserve draft and stop automatic retries',async()=>{const f=fixture();f.save=async()=>{throw Object.assign(new Error('changed'),{status:409});};f.change('x');await f.advance();assert.equal(f.controller.status,'conflict');assert.equal(f.timers.size,0);assert.equal(f.saved,'');});
test('validation and authorization failures preserve edits for correction',async()=>{for(const status of [400,401,403,422]){const f=fixture();f.save=async()=>{throw Object.assign(new Error('blocked'),{status});};f.change('x');await f.advance();assert.equal(f.controller.status,'error');assert.equal(f.timers.size,0);}});
test('retry flush saves after a recoverable failure',async()=>{const f=fixture();f.save=async()=>{throw new Error('offline');};f.change('x');await f.advance();f.save=async()=>{f.saved=f.value;};assert.equal(await f.controller.flush(),true);assert.equal(f.timers.size,0);});
test('switch reset cancels delayed writes from previous record',async()=>{const f=fixture();f.change('old');f.controller.reset();f.id='b';f.value=f.saved='';assert.equal(f.timers.size,0);assert.equal(f.calls.length,0);});
test('old response stays isolated while a new record queues its edit',async()=>{const f=fixture(),d=deferred();f.save=()=>d.promise;f.change('old');await f.advance();f.controller.reset();f.id='b';f.saved='';f.change('new');d.resolve();await tick();assert.notEqual(f.controller.status,'saved');f.save=async()=>{f.saved=f.value;};await f.advance();assert.deepEqual(f.calls,[{id:'a',value:'old'},{id:'b',value:'new'}]);});
test('stale flush returns false after record changes',async()=>{const f=fixture(),d=deferred();f.save=()=>d.promise;f.change('old');await f.advance();const flushed=f.controller.flush();f.controller.reset();f.id='b';f.value=f.saved='';d.resolve();assert.equal(await flushed,false);});
test('empty selection produces zero requests',async()=>{const f=fixture();f.id='';f.change('x');assert.equal(f.timers.size,0);assert.equal(await f.controller.flush(),true);assert.equal(f.calls.length,0);});
test('save redraw restores focus, caret selection and viewport',()=>{let focused,selection,scroll;const old={id:'',selectionStart:2,selectionEnd:4,selectionDirection:'forward',getAttribute:()=> '第31题修正答案'};const other={id:'',getAttribute:()=> '第32题修正答案'};const next={id:'',getAttribute:()=> '第31题修正答案',focus:()=>{focused=true;},setSelectionRange:(...args)=>{selection=args;}};let controls=[old];const container={contains:()=>true,querySelectorAll:()=>controls};const doc={activeElement:old,defaultView:{scrollX:0,scrollY:150,scrollTo:(...args)=>{scroll=args;}}};const restore=captureFocus(container,doc);controls=[other,next];restore();assert.equal(focused,true);assert.deepEqual(selection,[2,4,'forward']);assert.deepEqual(scroll,[0,150]);});
test('layout wires autosave ahead of app and exposes contextual retry',()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');assert.ok(html.indexOf('/static/review-autosave.js')<html.indexOf('/static/app.js'));assert.match(html,/修改结果后自动保存/);assert.match(html,/id="reviewAutosaveRetry"[^>]*hidden/);});
test('editing integration covers input, change, IME, reconnect and protected switching',()=>{const app=fs.readFileSync(path.join(__dirname,'../app.js'),'utf8');for(const text of ["['input','change']","compositionstart","compositionend","waitForReviewComposition()","await window.reviewAutosave.flush()","saveWorkspaceReview(false, true)","captureFocus(reviewEl.results)","window.addEventListener('online'"])assert.ok(app.includes(text),text);});
test('leave guard includes pending requests as well as local drafts',()=>{const workflow=fs.readFileSync(path.join(__dirname,'../workflow.js'),'utf8');assert.match(workflow,/workspaceReview\.hasDraft\(reviewState\) \|\| window\.reviewAutosave\?\.hasPending\(\)/);});
