(function(){
  const elements={
    list:document.querySelector('#templateList'),count:document.querySelector('#templateCount'),form:document.querySelector('#templateEditor'),
    editingId:document.querySelector('#templateEditingId'),title:document.querySelector('#templateEditorTitle'),name:document.querySelector('#templateName'),
    description:document.querySelector('#templateDescription'),source:document.querySelector('#templateSource'),sourceField:document.querySelector('#templateSourceField'),
    detail:document.querySelector('#templateDetail'),save:document.querySelector('#templateSave'),reset:document.querySelector('#templateReset'),
    remove:document.querySelector('#templateDelete'),status:document.querySelector('#templateStatus'),
    reviewSelect:document.querySelector('#reviewTemplateSelect'),scanSelect:document.querySelector('#scanTemplateSelect')
  };
  if(!elements.list)return;
  const state={templates:[],activeId:'',selectedId:''};
  function templateById(id){return state.templates.find(function(item){return item.id===id})}
  function setStatus(message,error){elements.status.textContent=message||'';elements.status.classList.toggle('error',Boolean(error))}
  async function request(url,payload){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload||{})});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'模板操作失败');return result}
  function fillSelect(select,preferred){if(!select)return;const previous=preferred||select.value||localStorage.getItem('omrTemplateId')||state.activeId;select.replaceChildren();state.templates.forEach(function(item){const option=document.createElement('option');option.value=item.id;option.textContent=item.name+(item.active?' · 当前默认':'');select.append(option)});select.value=templateById(previous)?previous:state.activeId}
  function renderSelectors(preferred){fillSelect(elements.reviewSelect,preferred);fillSelect(elements.scanSelect,preferred);elements.source.replaceChildren();state.templates.forEach(function(item){const option=document.createElement('option');option.value=item.id;option.textContent=item.name;elements.source.append(option)});elements.source.value=templateById(preferred)?preferred:state.activeId}
  function detailText(item){const recognition=item.recognition||{};const parts=[(recognition.page_count||'—')+' 页',recognition.question_range?'题号 '+recognition.question_range:'题号范围待设置',item.scan_ready?'扫描配置就绪':'扫描配置待补充',item.review_ready?'答题卡参考就绪':'答题卡参考待补充'];return parts.join(' · ')}
  function editTemplate(id){const item=templateById(id);if(!item)return;state.selectedId=id;elements.editingId.value=id;elements.title.textContent='编辑模板';elements.name.value=item.name||'';elements.description.value=item.description||'';elements.sourceField.hidden=true;elements.save.textContent='保存设置';elements.remove.hidden=Boolean(item.builtin);elements.detail.textContent=detailText(item);renderList()}
  function resetEditor(){state.selectedId='';elements.editingId.value='';elements.title.textContent='新建模板';elements.name.value='';elements.description.value='';elements.sourceField.hidden=false;elements.source.value=state.activeId;elements.save.textContent='创建模板';elements.remove.hidden=true;elements.detail.textContent='新模板会复制现有模板的定位、切割与扫描配置。';setStatus('')}
  function makeButton(label,className,handler){const button=document.createElement('button');button.type='button';button.className=className;button.textContent=label;button.addEventListener('click',handler);return button}
  function renderList(){elements.count.textContent=state.templates.length+' 套';elements.list.replaceChildren();state.templates.forEach(function(item){const card=document.createElement('article');card.className='template-card'+(item.id===state.selectedId?' selected':'')+(item.active?' active':'');const head=document.createElement('div');head.className='template-card-head';const title=document.createElement('strong');title.textContent=item.name;head.append(title);if(item.active){const badge=document.createElement('span');badge.className='template-active-badge';badge.textContent='当前默认';head.append(badge)}const description=document.createElement('p');description.textContent=item.description||'识别模板';const meta=document.createElement('div');meta.className='template-meta';meta.textContent=detailText(item);const actions=document.createElement('div');actions.className='template-card-actions';actions.append(makeButton('编辑','text-link',function(){editTemplate(item.id)}));if(!item.active)actions.append(makeButton('设为默认','text-link template-activate',async function(){try{setStatus('正在切换模板…');const result=await request('/api/templates/activate',{template_id:item.id});localStorage.setItem('omrTemplateId',item.id);applyResult(result,item.id);setStatus('默认模板已切换为“'+item.name+'”。')}catch(error){setStatus(error.message,true)}}));card.addEventListener('click',function(event){if(event.target.closest('button'))return;editTemplate(item.id)});card.append(head,description,meta,actions);elements.list.append(card)})}
  function applyResult(result,preferred){state.templates=result.templates||[];state.activeId=result.active_template_id||'';renderSelectors(preferred||state.activeId);renderList();window.dispatchEvent(new CustomEvent('templates:updated',{detail:result}))}
  async function loadTemplates(){try{const response=await fetch('/api/templates',{cache:'no-store'});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'读取模板失败');applyResult(result,localStorage.getItem('omrTemplateId'));resetEditor()}catch(error){setStatus(error.message,true)}}
  elements.form.addEventListener('submit',async function(event){event.preventDefault();const editingId=elements.editingId.value;const payload={name:elements.name.value.trim(),description:elements.description.value.trim()};try{elements.save.disabled=true;setStatus(editingId?'正在保存模板…':'正在创建模板…');let result;if(editingId){payload.template_id=editingId;result=await request('/api/templates/update',payload)}else{payload.source_template_id=elements.source.value;result=await request('/api/templates/create',payload)}const selected=result.template&&result.template.id||editingId;applyResult(result,selected);editTemplate(selected);setStatus(editingId?'模板设置已保存。':'模板副本已创建。')}catch(error){setStatus(error.message,true)}finally{elements.save.disabled=false}});
  elements.reset.addEventListener('click',resetEditor);
  elements.remove.addEventListener('click',async function(){const item=templateById(elements.editingId.value);if(!item)return;if(!window.confirm('删除模板“'+item.name+'”？'))return;try{elements.remove.disabled=true;setStatus('正在删除模板…');const result=await request('/api/templates/delete',{template_id:item.id});applyResult(result,result.active_template_id);resetEditor();setStatus('模板已删除。')}catch(error){setStatus(error.message,true)}finally{elements.remove.disabled=false}});
  [elements.reviewSelect,elements.scanSelect].forEach(function(select){if(select)select.addEventListener('change',function(){localStorage.setItem('omrTemplateId',select.value);const peer=select===elements.reviewSelect?elements.scanSelect:elements.reviewSelect;if(peer&&templateById(select.value))peer.value=select.value})});
  loadTemplates();
})();
